services:
  caddy:
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    image: caddy:latest
    restart: unless-stopped
    cpu_shares: 2048
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ${CONFIG_PATH}/${CONTAINER_NAME}/Caddyfile:/etc/caddy/Caddyfile
      - ${CONFIG_PATH}/${CONTAINER_NAME}/caddy/data:/data
      - ${CONFIG_PATH}/${CONTAINER_NAME}/config:/config
